#%RAML 1.0
title: Common API
version: v1

description: Common API allows you to obtain data on space stations and rockets owned by a particular space agency, 
             and launches made by this rocket. In addition, this API allows you to create a space agency database 
             based on data collected and filtered from multiple APIs.

documentation:
  - title: Common API
    content: This API refers for information to such web services as http://localhost:8083/station, 
             http://localhost:8088/planets, http://localhost:8085/launchesByStatusAndYear,
             http://lldev.thespacedevs.com/2.2.0/config/launcher/

types:
  AgencyDetailedMode: !include data_types/agency_detailed_data_types.raml
  AgencyNormalMode: !include data_types/agency_normal_data_types.raml
  AgencyListMode: !include data_types/agency_list_data_types.raml
  InfoByAgencyAndYear: !include data_types/info_by_agency_n_year_data_types.raml
  
/agencies:
  get:
    displayName: Get Agencies
    description: Retrieves information about launches, rockets and space stations by agency name.
    queryParameters:
      name:
        required: false
      mode:
        required: false
      limit:
        required: false
      offset:
        required: false
    responses:
      200:
        body:
          application/json:
            examples: 
              detailed: 
                type: AgencyDetailedMode[]
                example: !include examples/agency_detailed_example.json
              normal:
                type: AgencyNormalMode[]
                example: !include examples/agency_normal_example.json
              list:
                type: AgencyListMode[]
                example: !include examples/agency_list_example.json
      400:
        body:
          application/json:
            properties:
              message: string
            example:
              {
                message: "Invalid request"
              }

/infoByAgencyAndYear:
  get:
    displayName: Get Info By Agency And Year
    description: Retrieves information about space launches made by a given agency in a given year, space stations active 
                 in that year, owned by that agency, and solar system objects discovered in that year
    queryParameters:
      name:
        required: false
      launch_year:
        required: false
      limit:
        required: false
      offset:
        required: false
    responses:
      200:
        body:
          application/json:
            type: InfoByAgencyAndYear[]
            example: !include examples/info_by_agency_n_year_example.json
      400:
        body:
          application/json:
            properties:
              message: string
            example:
              {
                message: "Invalid request"
              }
/database:
  post:
    body:
      application/json:
        type: AgencyDetailedMode[]
        example: !include examples/agency_detailed_example.json
    responses:
      200:
        body:
          application/json:
            example:
              {
                message: "Record added"
              }
      400:
        body:
          application/json:
            example:
              {
                message: "Record wasn't added"
              }